-- 코드를 입력하세요
SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(B.PRICE*BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS
JOIN BOOK AS B ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR AS A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE,"%Y-%m") = "2022-01"
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;