-- 코드를 작성해주세요

WITH TEMP AS (SELECT A.ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA AS A
INNER JOIN ECOLI_DATA AS B
ON A.ID = B.PARENT_ID
GROUP BY ID)

SELECT E.ID, IFNULL(TEMP.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT OUTER JOIN TEMP
ON E.ID = TEMP.ID;