-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM (
    SELECT I.ANIMAL_ID, I.NAME,DATEDIFF(O.DATETIME,I.DATETIME) AS DATE
    FROM ANIMAL_INS AS I
    INNER JOIN ANIMAL_OUTS AS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DATE DESC
    LIMIT 2) AS A;