-- 코드를 입력하세요
# WITH TEMP AS(SELECT DISTINCT(C.CAR_ID),C.CAR_TYPE,C.DAILY_FEE
# FROM CAR_RENTAL_COMPANY_CAR AS C
# LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
# ON C.CAR_ID = H.CAR_ID
# WHERE CAR_TYPE IN ('SUV','세단')
# AND (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
# OR (H.START_DATE IS NULL AND H.END_DATE IS NULL))


WITH TEMP AS(SELECT C.CAR_ID,C.CAR_TYPE,C.DAILY_FEE,P.DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE CAR_ID NOT IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE<'2022-12-01' AND END_DATE>='2022-11-01')
AND P.DURATION_TYPE = '30일 이상')
 

SELECT DISTINCT(CAR_ID), CAR_TYPE, 
CASE
    WHEN CAR_TYPE = "세단" THEN ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100,0)
    ELSE  ROUND(DAILY_FEE * 30 *(100-DISCOUNT_RATE)/100,0)
END AS FEE
FROM TEMP
WHERE CAR_TYPE IN ('SUV','세단')
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC,CAR_TYPE ASC,CAR_ID DESC;
    