-- 코드를 입력하세요

WITH A AS(
SELECT FOOD_TYPE,MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE)




SELECT B.FOOD_TYPE,B.REST_ID,B.REST_NAME, B.FAVORITES
FROM REST_INFO AS B
INNER JOIN A
WHERE A.FOOD_TYPE = B.FOOD_TYPE
AND A.FAVORITES = B.FAVORITES
ORDER BY B.FOOD_TYPE DESC;
