
# WITH A AS (SELECT *
# FROM REST_INFO
# GROUP BY FOOD_TYPE)
      
# SELECT FOOD_TYPE,REST_ID,REST_NAME,MAX(FAVORITES) AS FAVORITES
# FROM A;

WITH A AS (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO 
GROUP BY FOOD_TYPE)

SELECT A.FOOD_TYPE, I.REST_ID,I.REST_NAME,I.FAVORITES
FROM REST_INFO AS I
INNER JOIN A
WHERE I.FOOD_TYPE = A.FOOD_TYPE
AND I.FAVORITES=A.FAVORITES
ORDER BY FOOD_TYPE DESC;