-- 코드를 작성해주세요
SELECT T.ID, 
CASE 
    WHEN T.PERCENT<=0.25 THEN "CRITICAL"
    WHEN T.PERCENT<=0.5 THEN "HIGH"
    WHEN T.PERCENT<=0.75 THEN "MEDIUM"
    ELSE "LOW"
END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
FROM ECOLI_DATA) AS T
ORDER BY ID;