-- 코드를 입력하세요
SELECT I.ANIMAL_ID,I.ANIMAL_TYPE,I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE IN('Intact Male','Intact Female')
AND O.SEX_UPON_OUTCOME IN('Neutered Male','Spayed Female')
ORDER BY ANIMAL_ID;