-- 코드를 입력하세요
SELECT V.REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,ROUND(AVG(V.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I
INNER JOIN REST_REVIEW AS V
WHERE I.REST_ID = V.REST_ID 
AND I.ADDRESS LIKE "서울%"
GROUP BY REST_ID
ORDER BY SCORE DESC ,FAVORITES DESC;