-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE AS O
INNER JOIN USER_INFO AS U
WHERE O.USER_ID = U.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH,GENDER
ORDER BY YEAR, MONTH,GENDER;

