-- 코드를 입력하세요
WITH TEMP AS (SELECT *
FROM USER_INFO 
WHERE YEAR(JOINED) = 2021)

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(*) FROM TEMP) ,1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS S
INNER JOIN TEMP
ON S.USER_ID = TEMP.USER_ID
GROUP BY YEAR, MONTH;


