-- 코드를 입력하세요
# SELECT P.PRODUCT_ID,P.PRODUCT_NAME
# FROM FOOD_ORDER AS O
# INNER JOIN FOOD_PRODUCT AS P
# ON I.PRODUCT_ID = P.PRODUCT_ID
# WHERE YEAR(P.PRODUCE_DATE) = '2022';

SELECT P.PRODUCT_ID,P.PRODUCT_NAME, P.PRICE*O.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
INNER JOIN (SELECT PRODUCT_ID,SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER 
WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE)='05'
GROUP BY PRODUCT_ID) AS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC,PRODUCT_ID;
