WITH A AS (SELECT HISTORY_ID, CAR_ID,END_DATE,START_DATE,
CASE 
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN "90일 이상"
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN "30일 이상"
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 THEN "7일 이상"
    ELSE NULL
           
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT HISTORY_ID,ROUND(C.DAILY_FEE * (100-IFNULL(P.DISCOUNT_RATE,0))/100 * (DATEDIFF(A.END_DATE,A.START_DATE)+1))AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN A
ON C.CAR_ID = A.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON P.CAR_TYPE = C.CAR_TYPE AND P.DURATION_TYPE = A.DURATION_TYPE
WHERE C.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC;



