-- 코드를 입력하세요
WITH A AS (
    SELECT H.HISTORY_ID ,C.CAR_TYPE, C.DAILY_FEE,DATEDIFF(H.END_DATE,H.START_DATE) + 1 AS PERIOD,
    CASE
        WHEN DATEDIFF(H.END_DATE,H.START_DATE) +1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE,H.START_DATE) +1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE,H.START_DATE) +1 >= 7 THEN '7일 이상'
        ELSE 'NONE'
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR  AS C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        ON C.CAR_ID = H.CAR_ID
        AND C.CAR_TYPE = '트럭'
)

SELECT A.HISTORY_ID, ROUND(A.PERIOD*A.DAILY_FEE*(100-IFNULL(P.DISCOUNT_RATE,0))/100) AS FEE
FROM A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON A.CAR_TYPE=P.CAR_TYPE
    AND A.DURATION_TYPE=P.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;


