# 2022-04-13일에 잡힌 진료중, 최소 되지 않은 에약을 조회하는 문제
SELECT A.APNT_NO, P.PT_NAME,A.PT_NO,A.MCDP_CD,D.DR_NAME,A.APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN PATIENT AS P
ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR AS D
ON A.MDDR_ID = D.DR_ID
WHERE A.APNT_YMD LIKE '2022-04-13%'
AND A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;