-- 코드를 작성해주세요
WITH A AS (SELECT CODE
FROM SKILLCODES
WHERE CATEGORY = "Front End")

SELECT DISTINCT ID,EMAIL,FIRST_NAME,LAST_NAME
FROM DEVELOPERS AS D
cross JOIN A
WHERE (D.SKILL_CODE & A.CODE) = A.CODE
ORDER BY ID;