-- 코드를 작성해주세요
SELECT DISTINCT(D.ID),D.EMAIL,D.FIRST_NAME,D.LAST_NAME
FROM DEVELOPERS AS D
CROSS JOIN (SELECT CODE
FROM SKILLCODES
WHERE CATEGORY = "Front End") AS C
WHERE C.CODE & D.SKILL_CODE = C.CODE
ORDER BY ID;
