-- 코드를 작성해주세요
WITH A AS (SELECT T.ITEM_ID, I.RARITY
FROM ITEM_INFO AS I
INNER JOIN ITEM_TREE AS T
WHERE I.ITEM_ID = T.PARENT_ITEM_ID
AND I.RARITY = 'RARE')

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
INNER JOIN A
WHERE I.ITEM_ID = A.ITEM_ID
ORDER BY ITEM_ID DESC;