-- 코드를 작성해주세요

WITH A AS(
    SELECT YEAR(DIFFERENTIATION_DATE)AS YEAR,MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)



SELECT A.YEAR, (A.MAXSIZE-E.SIZE_OF_COLONY)AS YEAR_DEV,ID
FROM ECOLI_DATA AS E
INNER JOIN A
ON A.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV ;
