-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT
FROM (SELECT I.FISH_TYPE,N.FISH_NAME
    FROM FISH_INFO AS I
    INNER JOIN FISH_NAME_INFO AS N
    WHERE I.FISH_TYPE = N.FISH_TYPE) B
WHERE B.FISH_NAME IN ('BASS','SNAPPER');