-- 코드를 입력하세요
SELECT F.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유')
GROUP BY CATEGORY) A
WHERE A.CATEGORY= F.CATEGORY 
    AND A.MAX_PRICE=F.PRICE
ORDER BY MAX_PRICE DESC;


