-- 코드를 입력하세요
SELECT TEMP.PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM (
SELECT PRODUCT_ID,
CASE 
    WHEN PRICE<10000 THEN 0
    ELSE FLOOR(PRICE/10000) *10000
END AS PRICE_GROUP
FROM PRODUCT) TEMP
GROUP BY TEMP.PRICE_GROUP
ORDER BY TEMP.PRICE_GROUP;
